export default {
  version: 8,
  name: "Relief shading",
  metadata: {
    "mapbox:autocomposite": true,
    "mapbox:type": "default",
    "mapbox:origin": "outdoors-v10",
    "mapbox:groups": {},
    "mapbox:trackposition": false,
    "mapbox:print": {
      units: "in",
      width: 8.5,
      height: 11,
      resolution: 300,
      format: "png",
    },
    "mapbox:sdk-support": { js: "0.40.0", android: "5.2.0", ios: "3.7.0" },
  },
  center: [-124.52062632246464, 49.97947883197557],
  zoom: 6.663522531392252,
  bearing: 0,
  pitch: 0,
  terrain: { source: "mapbox://mapbox.terrain-rgb" },
  sources: {
    "mapbox://mapbox.terrain-rgb": {
      url: "mapbox://mapbox.terrain-rgb",
      type: "raster-dem",
      tileSize: 256,
    },
    composite: {
      url: "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7",
      type: "vector",
    },
  },
  sprite:
    "mapbox://sprites/jczaplewski/cjftzyqhh8o5l2rqu4k68soub/ck2u8j60r58fu0sgyxrigm3cu",
  glyphs: "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "background",
      type: "background",
      layout: {},
      paint: { "background-color": "hsl(0, 0%, 90%)" },
    },
    {
      layout: {},
      filter: ["==", "class", "crop"],
      type: "fill",
      source: "composite",
      id: "crops",
      paint: {
        "fill-color": "#ceeb82",
        "fill-opacity": 0.5,
        "fill-antialias": false,
      },
      "source-layer": "landcover",
    },
    {
      layout: {},
      filter: ["==", "class", "grass"],
      type: "fill",
      source: "composite",
      id: "grass",
      paint: {
        "fill-color": "#b6e884",
        "fill-opacity": 0.75,
        "fill-antialias": false,
      },
      "source-layer": "landcover",
    },
    {
      layout: {},
      filter: ["==", "class", "wood"],
      type: "fill",
      source: "composite",
      id: "woods",
      paint: {
        "fill-color": "#63c77d",
        "fill-opacity": 0.21,
        "fill-antialias": false,
      },
      "source-layer": "landcover",
    },
    {
      layout: {},
      filter: ["==", "class", "national_park"],
      type: "fill",
      source: "composite",
      id: "national-parks",
      paint: { "fill-color": "hsl(100, 59%, 76%)", "fill-opacity": 0.75 },
      "source-layer": "landuse_overlay",
    },
    {
      layout: {},
      filter: ["==", "class", "sand"],
      type: "fill",
      source: "composite",
      id: "sand",
      paint: { "fill-color": "hsl(61, 72%, 72%)" },
      "source-layer": "landuse",
    },
    {
      minzoom: 9,
      layout: {},
      filter: ["==", "class", "glacier"],
      type: "fill",
      source: "composite",
      id: "glacier",
      paint: { "fill-color": "hsl(0, 100%, 100%)" },
      "source-layer": "landuse",
    },
    {
      layout: {},
      filter: ["==", "class", "snow"],
      type: "fill",
      source: "composite",
      id: "snow",
      paint: { "fill-color": "hsl(0, 0%, 100%)", "fill-antialias": false },
      "source-layer": "landcover",
    },
    {
      id: "water",
      type: "fill",
      source: "composite",
      "source-layer": "water",
      layout: {},
      paint: {
        "fill-color": {
          base: 1,
          stops: [
            [6, "#9cdaf4"],
            [10, "#7ab2ea"],
          ],
        },
      },
    },
    {
      layout: {},
      filter: ["in", "class", "wetland", "wetland_noveg"],
      type: "fill",
      source: "composite",
      id: "wetlands",
      paint: {
        "fill-color": {
          base: 1,
          stops: [
            [6, "#9cdaf4"],
            [10, "#7ab2ea"],
          ],
        },
      },
      "source-layer": "landuse_overlay",
    },
    {
      minzoom: 8,
      layout: {
        "line-cap": {
          base: 1,
          stops: [
            [0, "butt"],
            [11, "round"],
          ],
        },
        "line-join": "round",
      },
      filter: ["in", "class", "canal", "river", "stream"],
      type: "line",
      source: "composite",
      id: "waterways",
      paint: {
        "line-color": "#7ab2ea",
        "line-width": {
          base: 1.3,
          stops: [
            [8.5, 1],
            [20, 8],
          ],
        },
      },
      "source-layer": "waterway",
    },
    {
      id: "hillshading",
      type: "hillshade",
      source: "mapbox://mapbox.terrain-rgb",
      layout: {},
      paint: {
        "hillshade-illumination-anchor": "map",
        "hillshade-exaggeration": 1,
        "hillshade-highlight-color": "hsla(141, 63%, 49%, 0.75)",
        "hillshade-shadow-color": "#000000",
        "hillshade-accent-color": "hsl(57, 77%, 76%)",
        "hillshade-illumination-direction": 0,
      },
    },
  ],
  created: "2018-04-10T18:26:19.254Z",
  modified: "2021-12-06T11:26:55.260Z",
  id: "cjftzyqhh8o5l2rqu4k68soub",
  owner: "jczaplewski",
  visibility: "public",
  protected: false,
  draft: false,
};
